name: Preview Cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  remove:
    name: Remove preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - name: Remove PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
